### ISSUE TITLE
AniChart API

### ISSUE THREAD

**Issue by ratan12** [Josh-Star/AniList-API-Docs#27]
Are you planning to release an API for AniChart?
It would be nice to add a schedule in our application for Anilist and MAL.
The website supports MAL & AniList endpoint so it would have be nice.

Hope to hear from you soon.

**Comment by Josh-Star** [comment]
AniChart is kinda a one trick pony in that _all_ it really does is just provided seasonal data, so I don't really think (at least for now) it would be the best idea for us to open it up via an API.

However all the AniChart data is just from AniList, and we do provide [season API endpoints](http://anilist-api.readthedocs.org/en/latest/anime.html#browse), they have a slightly different data set then AniChart, but should be enough for a simple season/airing page. As discussed before (#13) I'm afraid we won't be providing Mal ids via the AniList API.

**Comment by ratan12** [comment]
My main problem with the API endpoint is that your using multiple pages... So if I want to make a schedule I need to make multiple requests and process it multiple times which is taking much time + more effort at the dev side.

Oh and don't forget once I progressed them I need to sort it on date and name.

I am not sure if it also provides the new episode number.

If you could output all the details in one endpoint it would be great!

**Comment by Josh-Star** [comment]
I'm currently working on a revamp of the browse pages so I have a look into providing single pages for the airing and seasonal entries. You'll also be able to request a retrieval order too.

At the moment /airing does include the episode airing data, though seasons don't, I'll fix this in the new browse version though.

**Comment by blitzprog** [comment]
I agree on the multi-page part. Being able to retrieve them all at once would make it easier to work with.

**Comment by ke352802081770314** [comment]
Many thanks for providing the season endpoint and browse/* in general.
The paging issue aside (I didn't find it that hard to code a loop for that), I think it would be really nice if we could retrieve a list of full anime models instead of small anime models.
To be able to render something with the information level of Anichart, we need information such as source, (main) studio, genres, description which are not contained in the small model, so after fetching the browse/... list, currently we need to retrieve anime/NNN/page for each of the titles.
I wouldn't mind if the characters/actors and reviews are left out but some others may have different preferences.
What would be cool is to have an additional parameter (besides page=N) being model={small|extended|page} with small being default (as it is now), page being everything the anime/NNN/page delivers and extended being something in between (especially without the characters/actors which would be wasteful to retrieve if it wasn't needed)

**Comment by Josh-Star** [comment]
New browse api is now live with a bunch of stuff including a fullpage option for seasons and currently airing shows, will update the docs in the next couple days. Old browse end points will still be supported but its recommended to update if you can.

**Comment by Josh-Star** [comment]
@ke352802081770314 I'm afraid our systems just don't support the flexibility of providing different models like that at the moment. In the future when we update/change frameworks its something I'll definitely look into.

**Comment by Josh-Star** [comment]
[Docs for new browse api are now up.](http://anilist-api.readthedocs.org/en/latest/anime.html#browse) Includes a full_page and airing_data option along with a bunch of other stuff

**Comment by ke352802081770314** [comment]
Many thanks for the update. A good improvement offering more flexibility.
Do you think it would be possible to allow a list in "type" as you do in "genres", e.g. type=Tv,Tv Short or type=OVA,ONA,Special ? (I also tried type=Tv&type=Tv Short but it's "latest wins", not merge.)
Again, many thanks for the great work you're doing!
